version: '2'
services:
  paxosa:
    build: .
    image: paxos
    expose:
      - 5555
    command: paxosa:5555 paxosb:5555 paxosc:5555

  paxosb:
    image: paxos
    depends_on:
      - paxosa
    expose:
      - 5555
    command: paxosb:5555 paxosc:5555

  paxosc:
    image: paxos
    depends_on:
      - paxosa
    expose:
      - 5555
    command: paxosc:5555